Add relative paths test

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -405,6 +405,90 @@ workflows:
               exit 1
             fi
 
+  glob_relative_checks:
+      description: |
+          Tests if relative globbing works.
+      envs:
+      - TMP_DIR: $ORIG_BITRISE_SOURCE_DIR/_tmp_relative_glob
+      - CACHE_PATH: |
+          ~/.bitrise/**/*.yml -> ~/.bitrise/plugins/spec.yml
+          ./DoesNotExist/
+          ./DoesNotExist/ -> ./doesnotexist.yml
+          ./DoesNotExist
+          ~/DoesNotExist
+          ~/.bitrise/plugins/step/*/*.go
+      steps:
+      - script:
+            title: Cleanup $TMP_DIR and archive tmp files
+            inputs:
+            - content: rm -rf "$TMP_DIR" "/tmp/cache-archive.tar" "/tmp/cache-info.json"
+      - script:
+            title: Create sample files
+            is_always_run: true
+            inputs:
+            - content: |-
+                  #!/bin/bash
+                  set -ex
+
+                  mkdir $TMP_DIR
+                  mkdir $TMP_DIR/cache
+                  echo "content" > $TMP_DIR/cache/foo.txt
+                  mkdir $TMP_DIR/cache/1
+                  echo "content" > $TMP_DIR/cache/1/bar.txt
+                  echo "content" > $TMP_DIR/cache/1/baz.txt
+                  mkdir $TMP_DIR/cache/2
+                  echo "content" > $TMP_DIR/cache/2/qux.txt
+                  mkdir $TMP_DIR/cache/3
+      - change-workdir:
+            title: Switch working dir to $TMP_DIR/cache
+            inputs:
+            - path: $TMP_DIR/cache
+            - is_create_path: true
+      - path::./:
+            title: Step Test
+            is_always_run: true
+            run_if: true
+            is_skippable: false
+            inputs:
+            - compress_archive: true
+            - is_debug_mode: true
+            - cache_paths: ./**/*.txt
+      - script:
+            title: Check if stored structure exists
+            is_always_run: true
+            inputs:
+            - content: |-
+                  #!/bin/bash
+                  set -ex
+
+                  # remove CACHE_PATH to cleanup
+                  rm -rf $TMP_DIR/cache
+                  mkdir $TMP_DIR/cache
+                  cd $TMP_DIR/cache
+
+                  # extract the archive
+                  tar -xPf /tmp/cache-archive.tar
+
+                  if [ ! -f $TMP_DIR/cache/foo.txt ]; then
+                    echo "dir should exist"
+                    exit 1
+                  fi
+
+                  if [ ! -f $TMP_DIR/cache/1/bar.txt ]; then
+                    echo "dir should exist"
+                    exit 1
+                  fi
+
+                  if [ ! -f $TMP_DIR/cache/1/baz.txt ]; then
+                    echo "dir should exist"
+                    exit 1
+                  fi
+
+                  if [ ! -f $TMP_DIR/cache/2/qux.txt ]; then
+                    echo "dir should exist"
+                    exit 1
+                  fi
+
   glob_checks:
     description: |
       Tests if glob matching works.
