Adding cache info file to archive, which includes stack ID (#27)
* Adding cache info file to archive, which includes stack ID

* Rename stackVersions to stackVersionData

* Removing type fields from test as is unused, use time.Since instead of time.Now().Sub

* dep update

* Use path under /tmp for archive_info.json

* Repository path migration, dep update

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -15,6 +15,7 @@ workflows:
     - smoke_test
     - ignore_path_test
     - generic_fs_checks
+    - test-stack-version
     # - backward_compatibility_test
     steps:
     - go-list:
@@ -370,6 +371,56 @@ workflows:
 
             if [ "$(< $TMP_DIR/mysymlink)" != "$(< /tmp/test_cache_file.txt)" ]; then
               echo "file content mismatch"
+              exit 1
+            fi
+
+  test-stack-version:
+    description: |
+      Test that archive_info.json containing stack ID is created.
+    envs:
+    - TMP_DIR: $ORIG_BITRISE_SOURCE_DIR/_tmp_stack_version
+    - CACHE_PATH: |
+        $TMP_DIR
+    steps:
+    - script:
+        title: Cleanup $TMP_DIR and archive tmp files
+        inputs:
+        - content: rm -rf "$TMP_DIR" "/tmp/cache-archive.tar" "/tmp/cache-info.json"
+    - change-workdir:
+        title: Switch working dir to $TMP_DIR
+        inputs:
+        - path: $TMP_DIR
+        - is_create_path: true
+    - script:
+        title: Create sample files
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            # file in root
+            echo "content" > $TMP_DIR/test_file1.txt
+    - path::./:
+        title: Step Test
+        is_always_run: true
+        run_if: true
+        is_skippable: false
+        inputs:
+        - compress_archive: true
+        - is_debug_mode: true
+        - cache_paths: $CACHE_PATH
+    - script:
+        title: Check that archive_info.json exists
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -ex
+            # remove TMP_DIR to cleanup
+            rm -rf $TMP_DIR
+            # extract the archive
+            firstfile="$(tar -b 1024 -tf /tmp/cache-archive.tar | while read item ; do [[ "$item" =~ .* ]] && echo "$item" && break ; done )"
+            echo $firstfile
+            if [ $firstfile != "/tmp/archive_info.json" ]; then 
+              echo "archive_info.json not found as first file in archive"
               exit 1
             fi
 
