do not copy file bytes if it is not regular file (no mode bits are set) (#24)
* extra error messages

* added regular file check

* added extra comments and log

* added FS check for CI

* wired in CI check

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -14,7 +14,8 @@ workflows:
     after_run:
     - smoke_test
     - ignore_path_test
-    # - backwared_compatible_test
+    - generic_fs_checks
+    # - backward_compatibility_test
     steps:
     - go-list:
     - golint:
@@ -26,7 +27,7 @@ workflows:
         - other_options: -f ${GO_CODE_COVERAGE_REPORT_PATH}
         - CODECOV_TOKEN: "$CODECOV_UPLOAD_TOKEN"
 
-  backwared_compatible_test:
+  backward_compatibility_test:
     description: |
       Tests if the cache descriptor file is not changed compared to the previous stable step version.
     envs:
@@ -271,6 +272,104 @@ workflows:
             # .mp3 is part of the exclude list, should not exists
             if [ -f $TMP_DIR/test_exclude_ext.mp3 ]; then
               echo "File exists."
+              exit 1
+            fi
+
+  generic_fs_checks:
+    description: |
+      Tests if most of the FS file types are supported.
+    envs:
+    - TMP_DIR: $ORIG_BITRISE_SOURCE_DIR/_tmp_fs_check
+    - CACHE_PATH: |
+        $TMP_DIR
+    steps:
+    - script:
+        title: Cleanup $TMP_DIR and archive tmp files
+        inputs:
+        - content: rm -rf "$TMP_DIR" "/tmp/cache-archive.tar" "/tmp/cache-info.json"
+    - change-workdir:
+        title: Switch working dir to $TMP_DIR
+        inputs:
+        - path: $TMP_DIR
+        - is_create_path: true
+    - script:
+        title: Create sample files
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+
+            # file in root
+            echo "content" > $TMP_DIR/test_file1.txt
+
+            # file in subdir
+            mkdir $TMP_DIR/subdir
+            echo "content" > $TMP_DIR/subdir/test_file.mp3
+
+            # single dir
+            mkdir $TMP_DIR/single_dir
+
+            # symlink to a temp file
+            rm -rf /tmp/test_cache_file.txt
+            echo "content" > /tmp/test_cache_file.txt
+            ln -s /tmp/test_cache_file.txt $TMP_DIR/mysymlink
+            ln /tmp/test_cache_file.txt $TMP_DIR/myhardlink
+
+    - path::./:
+        title: Step Test
+        is_always_run: true
+        run_if: true
+        is_skippable: false
+        inputs:
+        - compress_archive: true
+        - is_debug_mode: true
+        - cache_paths: $CACHE_PATH
+    - script:
+        title: Check if stored structure exists
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            
+            # remove TMP_DIR to cleanup
+            rm -rf $TMP_DIR
+            # extract the archive
+            tar -xPf /tmp/cache-archive.tar
+
+            if [ -d $TMP_DIR/single_dir ]; then
+              echo "dir should not exist"
+              exit 1
+            fi
+
+            if [ ! -f $TMP_DIR/test_file1.txt ]; then
+              echo "file should exist"
+              exit 1
+            fi
+
+            if [ ! -f $TMP_DIR/subdir/test_file.mp3 ]; then
+              echo "file should exist"
+              exit 1
+            fi
+
+            if [ ! -f $TMP_DIR/mysymlink ]; then
+              echo "file should exist"
+              exit 1
+            fi
+
+            if [ ! -f $TMP_DIR/myhardlink ]; then
+              echo "file should exist"
+              exit 1
+            fi
+
+            if [ "$(< $TMP_DIR/myhardlink)" != "$(< /tmp/test_cache_file.txt)" ]; then
+              echo "file content mismatch"
+              exit 1
+            fi
+
+            if [ "$(< $TMP_DIR/mysymlink)" != "$(< /tmp/test_cache_file.txt)" ]; then
+              echo "file content mismatch"
               exit 1
             fi
 
