test splitten into multiple workflows and commented; missing step input wired in (compare_cache_info_path); create archiveFilePath dir

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -4,52 +4,101 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 app:
   envs:
   # define these in your .bitrise.secrets.yml
-  - BITRISE_CACHE_API_URL: $BITRISE_CACHE_API_URL
+  - BITRISE_CACHE_API_URL: $BITRISE_CACHE_API_URL # use file url scheme (file://) to create a cache archive in a local directory
   - BITRISE_CACHE_INFO_PATH: $BITRISE_CACHE_INFO_PATH
+  - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
 
 workflows:
-  test:
-    before_run:
-    - audit-this-step
+  backwared_compatible_test:
+    description: |
+      Test to make sure the cache descriptor file's format is not changing.
+    envs:
+    - TMP_DIR: $ORIG_BITRISE_SOURCE_DIR/_tmp3
+    - CACHE_PATH: |
+        $BITRISE_CACHE_DIR
+        ../_sample_artifacts/filestructure -> ../_sample_artifacts/filestructure/build/findme.test
+        ./DoesNotExist/
+        ./DoesNotExist
+        ~/DoesNotExist
+        /Does/not/exists
+        ~/.android -> ~/.lockfile
+        ../_sample_artifacts/ipas
+        ../_sample_artifacts/ipas/
+        ../_sample_artifacts/filestructure/build/test.bin
+    - IGNORE_PATH: |-
+        ../_sample_artifacts/filestructure/sub-dir
+        ~/DoesNotExists/This
+        !~/.android/dir
+        *.apk
     steps:
-    - go-list:
-    - golint:
-    - errcheck:
-    - go-test:
-    - codecov:
-        run_if: .IsCI
+    - script:
+        title: Cleanup $TMP_DIR and archive tmp files
         inputs:
-        - other_options: -f ${GO_CODE_COVERAGE_REPORT_PATH}
-        - CODECOV_TOKEN: "$CODECOV_UPLOAD_TOKEN"
+        - content: rm -rf "$TMP_DIR" "/tmp/cache-archive.tar" "/tmp/cache-info.json"
     - change-workdir:
-        title: Switch working dir to test / _tmp dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
+        title: Switch working dir to $TMP_DIR
+        inputs:
+        - path: $TMP_DIR
+        - is_create_path: true
+    - cache-push:
+        title: Latest released version
+        run_if: true
+        is_skippable: false
+        inputs:
+        - is_debug_mode: true
+        - cache_paths: $CACHE_PATH
+        - ignore_check_on_paths: $IGNORE_PATH
+    - script:
+        title: Current version
         run_if: true
         inputs:
-        - path: ./_tmp
-        - is_create_path: true
+        - content: mv "/tmp/cache-info.json" "/tmp/cache-info_orig.json"
+    - path::./:
+        title: Current version
+        run_if: true
+        is_skippable: false
+        inputs:
+        - is_debug_mode: true
+        - cache_paths: $CACHE_PATH
+        - ignore_check_on_paths: $IGNORE_PATH
     - script:
-        title: Download assets
+        title: Current version
+        run_if: true
         inputs:
         - content: |-
             #!/bin/bash
             set -ex
-            rm -rf ./_sample_artifacts
-            git clone https://github.com/bitrise-samples/sample-artifacts.git ./_sample_artifacts
+
+            if [ "$(cat /tmp/cache-info_orig.json)" != "$(cat /tmp/cache-info_orig.json)" ] ; then
+                echo "Cache descriptor file changed"
+                exit 1
+            fi
+
+  smoke_test:
+    description: |
+      Simple test to make sure the step is able to cache files
+      using some exclude and include paths.
+    envs:
+    - TMP_DIR: $ORIG_BITRISE_SOURCE_DIR/_tmp1
+    steps:
+    - script:
+        title: Cleanup $TMP_DIR and archive tmp files
+        inputs:
+        - content: rm -rf "$TMP_DIR" "/tmp/cache-archive.tar" "/tmp/cache-info.json"
     - change-workdir:
-        title: Switch working dir to test / _tmp dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
+        title: Switch working dir to $TMP_DIR
+        inputs:
+        - path: $TMP_DIR
+        - is_create_path: true
+    - script:
+        title: Download assets
+        inputs:
+        - content:  git clone https://github.com/bitrise-samples/sample-artifacts.git $TMP_DIR/_sample_artifacts
+    - change-workdir:
+        title: Switch working dir to $TMP_DIR/_workdir
         run_if: true
         inputs:
-        - path: ./_workdir
+        - path: $TMP_DIR/_workdir
         - is_create_path: true
     - path::./:
         title: Step Test
@@ -73,26 +122,45 @@ workflows:
             ~/DoesNotExists/This
             !~/.android/dir
             *.apk
+
+  ignore_path_test:
+    description: |
+      Tests if ignored file's change does not triggers new cache generation,
+      so the ignored file should remain as it was originally, even if it gets modified
+      betweeen two cache push step run.
+    envs:
+    - TMP_DIR: $ORIG_BITRISE_SOURCE_DIR/_tmp2
+    - CACHE_PATH: |
+        $TMP_DIR
+    - IGNORE_PATH: |
+        $TMP_DIR/test_ignorechanges.txt
+        !*.mp3
+    steps:
     - script:
-        title: Create another samples
+        title: Cleanup $TMP_DIR and archive tmp files
+        inputs:
+        - content: rm -rf "$TMP_DIR" "/tmp/cache-archive.tar" "/tmp/cache-info.json"
+    - change-workdir:
+        title: Switch working dir to $TMP_DIR
+        inputs:
+        - path: $TMP_DIR
+        - is_create_path: true
+    - script:
+        title: Create sample files
         is_always_run: true
         inputs:
         - content: |-
             #!/bin/bash
             set -ex
-            rm -rf /tmp/cache-archive.tar
-            rm -rf /tmp/cache-info.json
-            rm -rf ./another_samples
-            mkdir ./another_samples
 
             #should follow changes
-            echo "content" > ./another_samples/test_file1.txt
+            echo "content" > $TMP_DIR/test_file1.txt
 
             #should not exists
-            echo "content" > ./another_samples/test_exclude_ext.mp3
+            echo "content" > $TMP_DIR/test_exclude_ext.mp3
 
             #should exists but ignore changes
-            echo "content" > ./another_samples/test_ignorechanges.txt
+            echo "content" > $TMP_DIR/test_ignorechanges.txt
     - path::./:
         title: Step Test
         is_always_run: true
@@ -101,11 +169,8 @@ workflows:
         inputs:
         - compress_archive: true
         - is_debug_mode: true
-        - cache_paths: |
-            ./another_samples
-        - ignore_check_on_paths: |-
-            ./another_samples/test_ignorechanges.txt
-            !*.mp3
+        - cache_paths: $CACHE_PATH
+        - ignore_check_on_paths: $IGNORE_PATH
     - script:
         title: Store MD5 hash and check if file doesn't exists
         is_always_run: true
@@ -114,14 +179,21 @@ workflows:
             #!/bin/bash
             set -ex
             
-            rm -rf ./another_samples
+            # remove TMP_DIR to cleanup test_ignorechanges.txt file
+            rm -rf $TMP_DIR
+            # extract the archive to get the archived test_ignorechanges.txt file
             tar -xPf /tmp/cache-archive.tar
 
-            envman add --key MD5PREVIOUSLY --value $(md5 -q ./another_samples/test_ignorechanges.txt)
-            echo "content" >> ./another_samples/test_ignorechanges.txt
+            # export the MD5 hash of test_ignorechanges.txt file
+            # this file's content should remain as it is even if it gets modified
+            # since this files if in ignore list and no other files changed
+            envman add --key MD5PREVIOUSLY --value $(md5 -q $TMP_DIR/test_ignorechanges.txt)
 
-            #should not exists
-            if [ -f ./another_samples/test_exclude_ext.mp3 ]; then
+            # following cache should not update the archive even if this file changes
+            echo "content" >> $TMP_DIR/test_ignorechanges.txt
+
+            # .mp3 is part of the exclude list, should not exists
+            if [ -f $TMP_DIR/test_exclude_ext.mp3 ]; then
               echo "File exists."
               exit 1
             fi
@@ -133,11 +205,8 @@ workflows:
         inputs:
         - compress_archive: true
         - is_debug_mode: true
-        - cache_paths: |
-            ./another_samples
-        - ignore_check_on_paths: |-
-            ./another_samples/test_ignorechanges.txt
-            !*.mp3
+        - cache_paths: $CACHE_PATH
+        - ignore_check_on_paths: $IGNORE_PATH
     - script:
         title: Check if MD5 matches the previous one
         is_always_run: true
@@ -146,20 +215,41 @@ workflows:
             #!/bin/bash
             set -ex
             
-            rm -rf ./another_samples
+            # remove TMP_DIR to cleanup test_ignorechanges.txt file
+            rm -rf $TMP_DIR
+            # extract the archive to get the archived test_ignorechanges.txt file
             tar -xPf /tmp/cache-archive.tar
 
-            export MD5CURRENT=$(md5 -q ./another_samples/test_ignorechanges.txt)
+            # test_ignorechanges.txt was part of the ignore list, so it's change should not present in the archive
+            export MD5CURRENT=$(md5 -q $TMP_DIR/test_ignorechanges.txt)
             if [ "$MD5CURRENT" != "$MD5PREVIOUSLY" ]; then
               echo "MD5 changed."
               exit 1
             fi
 
-            #should not exists
-            if [ -f ./another_samples/test_exclude_ext.mp3 ]; then
+            # .mp3 is part of the exclude list, should not exists
+            if [ -f $TMP_DIR/test_exclude_ext.mp3 ]; then
               echo "File exists."
               exit 1
             fi
+
+  test:
+    before_run:
+    - audit-this-step
+    after_run:
+    - smoke_test
+    - ignore_path_test
+    - backwared_compatible_test
+    steps:
+    - go-list:
+    - golint:
+    - errcheck:
+    - go-test:
+    - codecov:
+        run_if: .IsCI
+        inputs:
+        - other_options: -f ${GO_CODE_COVERAGE_REPORT_PATH}
+        - CODECOV_TOKEN: "$CODECOV_UPLOAD_TOKEN"
 
   # ----------------------------------------------------------------
   # --- Utility workflows
